services:
  api:
    build: ./api
    ports:
      - "8001:8001"
    volumes:
      - ./api:/app
    environment:
      - PYTHONUNBUFFERED=1
      - API_BASE_URL=https://api.tools.tugra-dev.my.id

  web:
    build: ./web
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://api.tools.tugra-dev.my.id
    depends_on:
      - api
    restart: always