services:
  api:
    build: ./api
    ports:
      - "8001:8001"
    volumes:
      - ./api:/app
    environment:
      - PYTHONUNBUFFERED=1

  web:
    build: ./web
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: always